# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vbsRnbfbIZ-eDwzfhe_96_eVt7-4huH
"""

import pandas as pd
FBTUIT=pd.DataFrame({
                     'Ism':[ 'Durbek' , 'Zulayho', 'Sardor','Mohigul '] ,
                     'Familyasi':[ 'Halilov' ,'Qadamova' , 'Xontorayev','Abdullayeva' ],
                     'Kanferasi':['Axborot texnalogiyalari', 'Axborot texnalogiyalari', 'Axborot texnalogiyalari','Axborot texnalogiyalari'],
                     'Fan nomi':["sun'iy intellekt", "sun'iy intellekt","Ma'lumotlar tuzulmasi","Ma'lumotlar tuzulmasi"],
                     'Yashash manzili':[ 'Fargona shahar',  'Fargona shahar','Fargona shaxar','Fargona Shahar'],
                     'Telefon nomeri': [   '+998931453545','+998933022212' ,'+998955555555','+9989999999999'  ]




})
print (FBTUIT)

FBTUIT.to_excel( 'FBTUIT.xlsx', index= False,Sheet_name='Sheet1')

FBTUIT.to_excel( 'FBTUIT.xlsx', index= False,Sheet_name='Sheet1')

FBTUIT.to_excel('FBTUIT.xlsx')